site_name: davidnet
theme:
  name: material
  features:
    - navigation.sections
  logo: images/logos/logo1.svg
  palette: 
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
extra:
  footer: ""
extra_css:
  - stylesheets/cleanup.css
markdown_extensions:
  - admonition
plugins:
  - search
  - privacy